name: My First workflow

on:
  pull_request:

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: |
          echo "Ritesh Rana"

  say-bye:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: |
          echo "Bye!"
          echo "Ritesh Rana pull request"